<?php
class CategoryModel extends Model
{
 private function outletId(): int { if(function_exists('current_outlet_id')) return current_outlet_id(); $u=Auth::user()??[]; return (int)($u['outlet_id']??1) ?: 1; }
 private function slug(string $s): string { $s=strtolower(trim($s)); $s=preg_replace('/[^a-z0-9]+/','-',$s); return trim($s,'-') ?: 'kategori'; }
 public function productCategories(): array { $out=$this->outletId(); $pScope=outlet_scope_sql('p.outlet_id',$out); $pcScope=outlet_scope_sql('pc.outlet_id',$out); return $this->all("SELECT pc.*, COUNT(p.id) product_count FROM product_categories pc LEFT JOIN products p ON p.category_id=pc.id AND p.is_active=1 AND {$pScope['sql']} WHERE pc.is_active=1 AND {$pcScope['sql']} GROUP BY pc.id ORDER BY CASE WHEN pc.sort_order = 0 THEN 999 ELSE pc.sort_order END, pc.name", array_merge($pScope['params'], $pcScope['params'])); }
 public function rawCategories(): array { return $this->all("SELECT c.*, COUNT(rm.id) material_count FROM raw_material_categories c LEFT JOIN raw_materials rm ON rm.category_id=c.id GROUP BY c.id ORDER BY CASE WHEN c.sort_order = 0 THEN 999 ELSE c.sort_order END, c.name"); }
 public function variants(): array { $out=$this->outletId(); $pScope=outlet_scope_sql('p.outlet_id',$out); $pvScope=outlet_scope_sql('pv.outlet_id',$out); $pcScope=outlet_scope_sql('pc.outlet_id',$out); return $this->all("SELECT pv.id,pv.sku,pv.variant_name,pv.hpp,pv.selling_price,pv.is_active,p.name product_name,pc.name category_name,p.outlet_id product_outlet_id,pv.outlet_id variant_outlet_id FROM product_variants pv JOIN products p ON p.id=pv.product_id JOIN product_categories pc ON pc.id=p.category_id WHERE p.is_active=1 AND pv.is_active=1 AND pc.is_active=1 AND {$pScope['sql']} AND {$pvScope['sql']} AND {$pcScope['sql']} ORDER BY pv.is_active DESC,pc.name,p.name,pv.variant_name LIMIT 500", array_merge($pScope['params'], $pvScope['params'], $pcScope['params'])); }
 public function storeProductCategory(array $d): int { $name=trim($d['name']); $slug=$this->slug($name); $this->execSql("INSERT INTO product_categories (outlet_id,name,slug,sort_order,is_active,created_at,updated_at) VALUES (?,?,?,?,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name), sort_order=VALUES(sort_order), is_active=1, updated_at=NOW()",[$this->outletId(),$name,$slug,(int)($d['sort_order']??0)]); return (int)Database::connection()->lastInsertId(); }
 public function updateProductCategory(array $d): void { $this->execSql("UPDATE product_categories SET name=?, sort_order=?, updated_at=NOW() WHERE id=? AND outlet_id=?",[trim($d['name']??''), (int)($d['sort_order']??0), (int)($d['id']??0), $this->outletId()]); }
 public function deleteProductCategory(int $id): void { $c=$this->one("SELECT COUNT(*) c FROM products WHERE category_id=?",[$id])['c']; if($c>0) throw new Exception("Kategori tidak bisa dihapus karena masih digunakan oleh produk."); $this->execSql("DELETE FROM product_categories WHERE id=? AND outlet_id=?",[$id, $this->outletId()]); }
 public function storeRawCategory(array $d): int { $this->execSql("INSERT INTO raw_material_categories (name,sort_order) VALUES (?,?) ON DUPLICATE KEY UPDATE sort_order=VALUES(sort_order)",[trim($d['name']),(int)($d['sort_order']??0)]); return (int)Database::connection()->lastInsertId(); }
 public function updateRawCategory(array $d): void { $this->execSql("UPDATE raw_material_categories SET name=?, sort_order=? WHERE id=?",[trim($d['name']??''), (int)($d['sort_order']??0), (int)($d['id']??0)]); }
 public function deleteRawCategory(int $id): void { $c=$this->one("SELECT COUNT(*) c FROM raw_materials WHERE category_id=?",[$id])['c']; if($c>0) throw new Exception("Kategori bahan baku tidak bisa dihapus karena masih digunakan oleh bahan."); $this->execSql("DELETE FROM raw_material_categories WHERE id=?",[$id]); }
 public function recipeVariants(): array { $out=$this->outletId(); $pScope=outlet_scope_sql('p.outlet_id',$out); $pvScope=outlet_scope_sql('pv.outlet_id',$out); $pcScope=outlet_scope_sql('pc.outlet_id',$out); return $this->all("SELECT pv.id,pv.variant_name,pv.hpp,pv.selling_price,p.name product_name,pc.name category_name,COALESCE(r.total_hpp,0) recipe_hpp,p.outlet_id product_outlet_id,pv.outlet_id variant_outlet_id FROM product_variants pv JOIN products p ON p.id=pv.product_id JOIN product_categories pc ON pc.id=p.category_id LEFT JOIN recipes r ON r.product_variant_id=pv.id AND r.is_active=1 WHERE pv.is_active=1 AND p.is_active=1 AND pc.is_active=1 AND {$pScope['sql']} AND {$pvScope['sql']} AND {$pcScope['sql']} ORDER BY pc.name,p.name,pv.variant_name LIMIT 500", array_merge($pScope['params'], $pvScope['params'], $pcScope['params'])); }
}
